version: "2"

services:

  dev.localhost:
    build: ./
    image: dev.localhost:latest
    container_name: dev.localhost
    restart: 'no'
    environment:
      VIRTUAL_HOST: dev.localhost
    expose:
      - 80
    entrypoint: python /app/app.py
    volumes:
      - ./app:/app

networks:
  default:
    external:
      name: shared
